### ISSUE TITLE
[InvalidBug] Save Screenshot Crash caused by missing PNG lib in EmuCR build

### ISSUE THREAD

**Issue by jcdenton2k** [snes9xgit/snes9x#114]
Just wanted to see if anyone else is encountering this issue.  Completely default settings and it still happens so I am unsure whether it is an issue with their compilation/build or if it is an actual bug in the code somewhere.  Pressing 'Save Screenshot' (F12 by default) will cause the emulator to immediately crash every single time.

Using the precompiled Windows build from EmuCR that is current as of the April 16 2016 commit on this GitHub:

http://www.emucr.com/2016/04/snes9x-git-20160418.html

**Comment by bonimy** [comment]
Not sure if this issue belongs here. That build does indeed crash, but I just built the most recent source myself with default settings and got a screenshot just fine. I'm guessing the issue was how the author built it. You would have to contact them.

**Comment by jcdenton2k** [comment]
@bonimy if you built the windows version, could you post a link to the compiled version?  I'm sure I'm not the only one that would appreciate it :)

I tend to do all my compilation on Linux Mint because it is so much easier compared to Windows when it comes to compiling code.

**Comment by bonimy** [comment]
@jcdenton2k I'd be happy to send you the built version I have. Are you looking for an x86 or x64 Debug or Release build?

Building it in Windows is a huge pain. The source actually has a "how2compile" document that helps, but isn't perfect. I did a very detailed log of my experience getting the code to compile so I'll be happy to share it with you.

Also, Visual Studio is currently free and has been for some time now. You should check it out.
https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx

You'll also want VS2013 since you need its runtime to successfully build snes9x from a clean download.

Just send a reply or PM and I'll give you more information when I get back from work. And if you know anyone else that needs help building it in Windows, then you can either send them to make or I can make a public post somewhere.

**Comment by jcdenton2k** [comment]
@bonimy: I've gotten in touch with Orphis (of Orphis Buildbot fame) and am going to be asking them to do some automated builds for SNES9X like they already do for PCSX2 and PPSSPP.  Then I'm going to ask one of the SNES9X devs if I can be upgraded to maintainer of this project so that I can (slowly) start to integrate some of the fixes from forks into this version (since we are technically 'upstream' here).

I hope for SNES9X to be reborn into a unified all-in-one awesome version like what happened with the FCEUX emulator for NES.  Maybe the TAS stuff could be an option to enable/disable it but those features may be useful for even casual SNES players.

If you still wish to compile for me (and for others) then you are welcome to do so!
Currently need a Windows build for both x86 and x64 as a 'Release' build as of the latest commit here on the SNES9X github.

I would appreciate you posting a link to https://cryptbin.com/ with the log/instructions that you used to compile as I am quite sure it will benefit others who may have similar issues.

I sure as hell won't be able to maintain this alone so I'll poke as many SNES9X devs and fork-devs to see what can be done.  I would just fork this myself but it is about time someone stepped up to at least let people know that there is at least one current maintainer of this project.  It would be like if Debian devs suddenly all gave up and did zero updates for years and nobody bothered to go in and offer to keep maintaining it.  It would affect all the downstream distros pretty drastically.

**Comment by OV2** [comment]
The latest testbuild is up to date for the windows version (no relevant commits since then). The only relevant fork with changes that I know of would be the libretro s9x, which I shamefully neglected to merge changes from for the last two years. I have some free time in two weeks, maybe I can finally take that in.

Creating builds is not the problem, getting relevant changes done is.

**Comment by jcdenton2k** [comment]
I responded to you in https://github.com/snes9xgit/snes9x/issues/99 so we'll continue there.
