### ISSUE TITLE
Q: blocker for the new release?

### ISSUE THREAD

**Issue by jristz** [snes9xgit/snes9x#117]
As far I underestand the project is still on development but since last stable version has happened... like... 5 years I think.

I there a list of blockers bug somewhere to check or a possibility to do a 1.6-beta-01 release in the near future?
Peoples think that the project is dead and there are many bugs that the new release could fix (like one I have with a hack room in 1.53 but not in git and not forget the gtk3 think in linux)

If there a Blocklist, make it visible could lead to contributors know what need to be fixed to the next release.

so is there a blocklist or something preventing a new release, even a simple 1.6-apla-01?

**Comment by jcdenton2k** [comment]
We will be doing some new releases soon-ish:
https://github.com/snes9xgit/snes9x/issues/99

The main issue has been a lack of developers willing to continue working on this when other emulators (bsnes) have superceded it in accuracy.

I still believe SNES9X could continue to improve and offer a nice alternative for people who want a game to run full-speed on a system that isn't top of the line.  If a gaming computer with ultra-fast hardware is required to run even basic games at full speed then most people will just use something else.  SNES9X is the replacement for ZSNES in just about every way and if we improve our accuracy in ways that don't sacrifice too much performance then we could find that sweet spot that doesn't mandate perfect accuracy no matter what.

It takes a while but yeah.  If you know any emulator authors willing to dig around in the code and fix a few things then feel free.

According to this link:
http://tasvideos.org/EmulatorResources/SNESAccuracyTests.html

The SNES ADC SBC is not properly emulated at all in anything other than higan/bsnes.
SNES9X also fails the SNES OAM HIGH test.  Even if it may not seem necessary to emulation it wouldn't hurt to try to correct a few emulation things instead of continuing to use hacky workarounds.

If one of the authors wants to get in touch with Disch of RHDN and Disch actually wants to work on this then it would be an incredibly fantastic boon to emulation as a whole.

You can also get in touch with Bisqwit and see if they want to help:
http://bisqwit.iki.fi/utils/nesdelay.php

If we're really going to provide a viable/useful alternative to the bsnes/higan 'accuracy at all costs' then we would really need some great programmers to get it done (and have them have the free time to do it).

I feel going forward that nothing in emulation will drastically improve without some crowdfunding to get it done.

**Comment by bearoso** [comment]
The mentioned tests pass now. We've had two big releases since this issue opened.
