### ISSUE TITLE
[Enhancement] Overlay Support

### ISSUE THREAD

**Issue by shinra358** [snes9xgit/snes9x#134]
May I ask for the ability to load a custom .png file within the emulator, like the shaders, to create overlays for Snes9x?

Thanks in advance.

**Comment by OV2** [comment]
You can already do that with shaders - take a look at the shaders in the borders folder: https://github.com/libretro/common-shaders/tree/master/borders
imgborder.cgp should do what you want, and you can simply replace the png.

**Comment by shinra358** [comment]
Okay, thanks. But which value do I modify to remove the border but still show the png in the imgborder-1080p.cg file (loaded the particular png already)?

**Comment by shinra358** [comment]
So I asked the creators of those shaders to add opacity to that shader and they did. But there's a problem since it's a shader and not specifically an overlay (i guess?). With other effects, it blends in with said effects. So if I created a scanline png, depending on what postprocessing effects I have on, I can barely see the scanlines. I can see them if I put my face closer to the monitor, but 3 feet away, I can only see how light or dark the lines make the screen but not the actual lines. This isn't a problem with the retroarch or mame version of the overlay system. Because the effects there don't seem to blend together like that. What are your thoughts OV2?

**Comment by OV2** [comment]
I'm not sure what postprocessing effects you are talking about - the shaders are the last thing that are applied to the output image. Also if you just want scanlines, why not just use a scanlines shader?

**Comment by bearoso** [comment]
I think you're asking for such a special case that a custom shader would have to be written for you. The shaders OV2 pointed out are generally what people want and would be the same as if the overlay were built in. The overlay would not be passed in as part of the game image and subject to postprocessing.

**Comment by shinra358** [comment]
"I'm not sure what postprocessing effects you are talking about": any post processing effect used in unison with this.

 "the shaders are the last thing that are applied to the output image.": but since the scanlines are in shader form instead of overlay form, any blur or bloom, etc. post processing effect has an impact on a scanline png making them difficult to see. If it were a true overlay, the scanlines would be over everything and the effect wouldn't affect them.

"I think you're asking for such a special case that a custom shader would have to be written for you.": nah, just asking for an overlay selector so that whatever png I use is not affecting by any post processing effect. I wouldn't know what specific term I can use for that. 

"Also if you just want scanlines, why not just use a scanlines shader?": scanline effects from sweetfx, the collection of shaders that this uses, as well as most built in scanlines don't look very good. They are either always too thick, or clump together forming unevenness. The best scanlines i've seen are in pcsx2, epsxe, bsnes (after modding the thickness), retroarch (using a png overlay), and mame (using a png overlay).

So what I meant by overlay is having a slot where you can use an image and it sits on top of everything without being affected by blur, bloom, etc.

These are my scanlines with bloom for snes9x (50% opacity) (shader):
[url=https://postimg.org/image/5j2ed79fh/][img]https://s6.postimg.org/5j2ed79fh/snes9x_x64_2016_10_22_08_41_45.png[/img][/url]

You can't tell scanlines are even on. But you can if you put your nose to the screen.

These are my scanlines with bloom in mame (50% opacity) (overlay):
[url=https://postimg.org/image/hbgtkmph9/][img]https://s6.postimg.org/hbgtkmph9/mame64_2016_09_03_20_13_37.png[/img][/url]

you can tell they are there from 3 feet away.

Same scanlines setup with retroarch (overlay):
[url=https://postimg.org/image/gxfhl15dp/][img]https://s6.postimg.org/gxfhl15dp/retroarch_2016_08_16_12_45_38.png[/img][/url]

Same here. You can tell they are there.


I mean, shaders and overlays are supposed to work differently as explained correct (with the overlay not being affected by any of the shaders)? Let me know if I'm wrong or if it's just my imagination and I'll just close the thread no worries.

**Comment by bearoso** [comment]
It seems you have a problem concerning the transformation space the image is applied to. You want your image to be displayed 1:1 in screen space, with the scanlines every other line in the output. That's doable with shaders, it just doesn't reflect scanlines in the real world on CRTs, which is why you don't see anybody else who wants that.

**Comment by jcdenton2k** [comment]
Quick thing here.

In puNES (NES emulator here on github), the image can be modified by a software filter or a shader but not both.

PCSX2 is built in such a way that you can apply a 'scanline' filter (dubbed TV mode) in addition to an external custom filter through special files to add in additional post-processing effects.

I believe what the OP is asking for is something similar to what PCSX2 has rather than what SNES9X currently has or what puNES has done.  Not have to choose one or the other but to have both a custom scanline filtering applied over the image and additional post-processing via external configuration files (or SNES9X equivalent).

I'm not sure the SNES9X output can really handle that though.  PCSX2 has one significant advantage with the plugin architecture and that is the capability of making things modular like they are.  Not every emulator can pull that off and the retroactive compatibility of the code makes it difficult to do so without a complete re-write.

I personally use Blargg's NTSC RGB but you can also choose the Composite or S-Video versions if you like.  There's only so much 'fuzzing' you can do with filters to get it as close as you like.

One of the only games I know of that mandates such a filter (or a CRT) would be Blargg's MD NTSC filter for Kega Fusion (or the 'TV Mode CVBS' one) for Comix Zone.

I love how the games look with these filters, but I'd suggest for SNES9X to modify the existing filters for your own purposes (adjusting bloom/intensity/opacity as you like) within the confines of the existing setup.

To each their own, but you're asking for custom filtering just for your own particular needs.  After all, the best bet for REAL authenticity is playing on the original console with the original kart on a CRT.

**Comment by shinra358** [comment]
@bearoso No, my concern is having overlays where shaders do not affect them. All three pics use my custom made scanlines png file. When used in other emus (as seen in the pics above) you can see them nicely but using them in a shader, the effects from the shaders merge with it making it hardly noticable. So again, it's all about a layer that isn't affected by the layer that the shaders aren't on.

In ahk, I can make the same scanlines png cover the entire window. This would have the shaders not touch or interact with them at all, having the scanlines pure and untouched by blur, bloom, etc. since it it external. As you can see from mame and retroarch, the scanlines aren't touched by the internal shaders (except the external ones like reshade but that cant be helped) because it is an overlay and lays over the game and the shaders but is still within the window and not external like the ahk method.

It's that all 3 have the same exact png and same exact opacity but only one uses a different format and that same one, is the one that's hard to see the lines on. 


There are lots of ppl who want the 1080p type scanlines. I've seen lots over multple years and forums saying that the traditional 'accurate' scanlines don't look good. For example, in the mugen community, the mugen engine initially had scanlines built in. And they were the ones that I like here in these pics except they had no opacity so everyone turned them off because it made the picture too dark. They all still wanted the scanlines but opacity along with them. Eventually the mugen devs came along and updated the engine. And they took scanlines out this time. And everyone was upset and wanted them back.
https://www.youtube.com/watch?v=nJ7KmaDfuq8
^
The scanlines shown there are typically what the 'accurate' scanlines look like. The thing is, if looking at an arcade cabinet, they didn't look like that. They only looked like that when you put your eye like 1 pixel away from the screen. And everyone is contacted this dev to tell him to use better scanlines or just take them off. In his newer vids, it seems he decided to remove them since the desirable scanlines can't be edited the 'desireable' way in sweetx. 

But that's not my concern here because I can easily achieve this with the png and if the rez increases, I can easily may another png to compliment the new rez.


The traditional 'accurate' scanlines are uaually coded in a shader and don't account for other resolutions. instead of drawing more lines to fill the space, the lines are stretched which can cause uneven vertical clumping.

Edit: I was writing this before the prev poster posted. But i'll post this anyway since it's alot and I don't want to have written in vane lol. But yeah, he explained it good. Except I don't like scanlines because for nostalgia or trying to replicate the past, I like them because of how they make the picture look. But yeah, if it is going to be as much trouble as the prev poster said it could be, don't worry about it, it's no big deal.

**Comment by OV2** [comment]
Maybe you should post your setup where you have that issue. You say "scanlines with bloom" - the only way I can think of would be either a custom shader that does both, or a multi-shader cgp file.

I'm not sure I want to do the extra work for a separate overlay config. I did that for retroarch d3d, but there it makes more sense because it has touch support for on-screen buttons in the overlay.

**Comment by shinra358** [comment]
The scanlines are from the shader you recommended to me at the beginning. From snes9x, I'm using the 2xbrz. Then I'm using gaussian blur, and bloom from reshade. This same setup is used with everything including all pics I've already shown. I know reshade is an overall thing and this wouldnt  completely solve it because reshade is external. But it would solve it enough so that the other shaders from snes9x wouldn't affect therefore most likely making it like the other pics. But if it's too much, don't worry about it. I thought about switching to retroarch for snes9x but I needed a few questions first:

-what happens when you unplug a controller during game during a real snes game on the real console? Does it pause or does nothing happen (can't remember and is vital to my decision and my real snes is broken).

-are the xbrz scalers on the retroarch version?

**Comment by jcdenton2k** [comment]
-The game continues on like nothing happened.  Some games pause automatically depending on the game but it is very rare for that to happen.  Old school consoles like NES/SNES/Genesis didn't do anything when you unplugged the controller it just meant you can't control the game while the action continues.  I remember once or twice on Genesis the game would enter a pause screen automatically that says 'no controller found' but I can't remember the exact games.

-I don't know but I'm going to presume they are since the retroarch core version was custom-compiled for them based on the existing code here for the standalone version.

**Comment by shinra358** [comment]
I tried the retroarch version and it didn't have xbrz :(

As for the scanline issue, I figured it out. It was because of the fxaa in reshade. Now I'm able to see them like the others. So, I'm going to close this thread now.

I will just stick to this version and hope that the controller issue gets fixed again. Because even though retroarch doesn't have the controller issue, it doesn't have xbrz. OV2 was good in fixing it in the past so hopefully he could do that again. But if retroarch gets xbrz first, I'll go ahead and move to that. But I'd prefer controllers get fixed here so that the message would pause on those certain games when controller is disconnected to be able to have the pure hardware experience.
