### ISSUE TITLE
Found 3 bugs in Snes9x v1.54.1

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#141]
Can't turn off sound because  Mute is not working.  Also if I try to change playback rate it will crash the emulator I wanted to to be in 44KHz. When you go to the sound Driver and change it to FMOD EX Default it will crash the emulator.

**Comment by jcdenton2k** [comment]
Going to give my thoughts on these bugs.

1 - _Cannot turn off sound because Mute is not working_.  YES this is a bug but it affects FRAME ADVANCE MUTE not working.  Regular 'mute sound' works fine if done in Sound Settings or from the Playback Rate sound menu.  Frame Advance Mute does NOT currently work.

2 - _Change playback rate to 44 KHz._  YES this is a bug.  It works fine with 32, 35, and 48 KHz but for some reason bugs out badly ONLY with 44 KHz.

3 - _When you go to the sound driver and change it to FMOD EX Default then it will crash the emulator_.  YES this is a bug and I've confirmed that not only will it crash but afterwards it will CONTINUE to crash unless you manually edit the snes9x.conf to change it to another audio driver.  This also happens to FMOD EX OpenAL and FMOD EX ASIO with the crashing and crash-loop bug.  The XAudio2 and DirectSound options work fine for me.

**Comment by bonimy** [comment]
I tried Frame Advance Mute and the very first time, it did not work, as posted. However, after retoggling it, it worked properly. This working behavior persisted even when restarting the app, rebuilding, deleting the config file, and moving the app to a new folder. So I'm not sure how to consider looking for the issue. Maybe someone has some ideas?

I was able to tackle the second issue with more success. The source of the crash is due to a memory deallocation error occurring in `CXAudio2.cpp`: `void CXAudio2::DeInitVoices(void)`. The final `if`-statement deletes variable array `soundBuffer`. A crash implies memory was written out of range. Tracing the source of the `soundBuffer` write that causes a memory bound array, I was lead to `CXAudio2::ProcessSound()` in the same source file, to `S9xMixSamples` in `apu.cpp`, to `spc::resampler->read` in `hermite_resampler.h`. The array bound error happens inside the second while loop, where `data[o_position + 1]` is written to. This while loop assumes that `num_samples` be even so it can write to `data` twice. However, when the sound output is set to 44kHz, `num_samples` becomes `705`.

There are two ways to fix this, but I do not know the intricacies of the sound emulator, so I leave them to the more knowledgeable to determine it. We can either adjust `singleBufferSamples` to always be even, or we could modify the read function's loop to accommodate odd values.

I haven't looked at the third issue yet.

**Comment by bearoso** [comment]
The data read from the resampler is stereo, so the number of samples read should always be even. An odd number implies something else is broken.

**Comment by bonimy** [comment]
Okay. I vote we put an assert there for future bug catching.

**Comment by OV2** [comment]
I've already fixed this in the xaudio + directsound drivers and added an assert, just did not get around to push the commit yet.
The mute problem stems from the fact that savestating turns on mute, and turns it off after it is done. When rewind is on, this effectively breaks mute altogether. I've removed the mute calls and it still seemed to work fine - @bearoso can you think of any reason why mute would be necessary? It's been there since the initial 1.52 import.

**Comment by jcdenton2k** [comment]
Many people want working 'frame advance' mute.  Aka to 'turbo mode' temporarily without having to hear the sped up distorted sound/music.

**Comment by bearoso** [comment]
Don't know why mute would be needed there. It might be to reduce popping during save state load? I think it's safe to remove now, we can put it back if it's needed.

**Comment by OV2** [comment]
I've pushed the changes, should fix mute and the 44,1 khz crash.

Frame advance has nothing to do with turbo mode, it is the single step mode available via "Emulation->Frame advance"

FMOD is most likely crashing because you do not have the fmod dll - I did not include it in the 1.54 releases. You'll need to get it from the 1.54 zip file. It probably makes sense to remove them entirely at some point.

**Comment by jcdenton2k** [comment]
All dependencies should be noted or included during a release.  That's the first rule of packaging :P

**Comment by jjfmz42015** [comment]
Found another sound bug. Intro music just crashes in snes9x 1.54 or newer even in test builds chester cheetah: wild wild quest

This sound is ok in 1.53 it is also ok in bsnes/higan and ok in snesgt and gasp zsnes

**Comment by bearoso** [comment]
Now irrelevant.
