### ISSUE TITLE
[Request] Overclocking?

### ISSUE THREAD

**Issue by Electricstar** [snes9xgit/snes9x#158]
Hello. I thought i'd make a simple request to add overclocking to the emulator.
Every other request like this is always "SuperFX-exclusive/specific", but as far as I am aware, in emulation, All three major chips are overclockable: The main CPU, The SA-1, and the SuperFX chip and its variations.

MAME does this by actually overclocking the CPU with seemingly no issues unlike real hardware (I think), and ZSNES, as well as a custom Snes9x build I have on me, do this by method of not overclocking the CPU, but instead adding "Cycles per second", such as the ZSNES per2exec hack, and in this custom SNES9x I have, "Snes9xpp SE", Every CPU is "overclocked" using this hack. There are (seemingly) no issues aside from certain games running at a higher FPS than intended, the only more notable issue i've seen is Secret of Mana/Seiken Densetsu 2 having a corrupted title screen when maxing out the Cycles Per Second.

Regardless, it helps by almost COMPLETELY eliminating slowdown in all games i've tested, including the ones that do bug out. Some may argue, "Accuracy > Performance", but BSNES/Higan is already a perfect emulator in terms of accuracy. As well, it would be nice to at least have the option at all, given that the player can acknowledge that it _will_ break some games as the cost of making them run smoother.

**Comment by meepingsnesroms** [comment]
Yes overclocking an emulator would at most cause it to run too fast.(Since it cant overheat)
What games lag?(And where they designed to just be slow games?)

The only reason the SuperFX can be overclocked is because there is only 1 value regulating the opcodes per frame and the superfx has a "stop" opcode,so just setting max opcodes to infinite overclocks it by making it run until it hits a stop opcode.(that it is meant to hit before the end of each frame and when time rendering exceeds 1 frame it still finishes it,so 1 frame would take 1 + whatever time it needs to finish)

**Comment by jcdenton2k** [comment]
I've talked about this for a while and the devs basically said 'nope we won't do that' and if we want it done we have to play the special alternate fork of SNES9X which has that feature already built-in.

Kinda sucks but not even wanting to add it in as an OPTION is pretty narrow-minded of them :(

**Comment by bearoso** [comment]
At this point it is now impossible without simply speeding up everything, sound, framerate, etc. The master clock is tied to the PPU for accuracy, and all clocks are tied to the master clock by ratio. You'd have to get an older version of Snes9x, or an emulator like zsnes where the clocks are all still asynchronous, for any "overclocking." You could add some extra cycles in hblank or vblank or something, but that's something way too complex to put in a UI, because you'd need to tweak it for every use case, and it would affect more than speed.

The SuperFX can be messed with by tweaking the clock lines in it's own file, but that's only because Snes9x's SuperFX code sucks so badly (see Doom for example).
