### ISSUE TITLE
Compressed audio support in MSU-1

### ISSUE THREAD

**Issue by mudlord** [snes9xgit/snes9x#159]
Just wondering whether this is potentially something or will it be another thing I have to add in myself in a unofficial patch because:
1) byuu is too fucking incompetant to have a single inkling of compression (doesn't know math)
2) byuu is too fucking stubborn to accept patches that don't fit his code standards.
3) byuu refuses to accept leeway on his formats (most egregious since he cannot handle anyone doing any improvements to his formats, no matter who the person is)
4) byuu refuses to use any outside libraries and refuses to acknowledge anything thats not made by him (public domain mp3/vorbis/flac decoders exist, and WavPack has a BSD licensed decoder)

I have no hesitation if this falls through to just maintain a patch myself for people to use as the case may be.

**Comment by qwertymodo** [comment]
1) You do realize byuu wasn't the one who ported MSU-1 to Snes9x, and had absolutely nothing to do with it, right?

2) While I understand the wish for compressed audio files, from the perspective of somebody creating a hack, splitting the standard where some audio formats are supported by some emulators but not by others is an absolute nightmare for maintenance.  Even just fixing the audio levels now that the SD2SNES DAC is properly leveled is a colossal pain in the neck.  Trust me, I'm the one spearheading that particular workload.  Nobody wants to go through that all again.  I'm surprised Conn has even gone for my fixes, I can guarantee he won't be at all interested in going down that road again.

2a) Regardless of whether or not higan/bsnes supports such files in the future, the SD2SNES won't, so whining about byuu's inflexibility isn't really the issue here.

Realistically, OV2's zip support is the best option going forward.  Compressed audio format support is just a nightmare waiting to happen for everybody involved.

**Comment by mudlord** [comment]
1. Good, I prefer he had touched nothing of it.
2. Fair enough, especially when a certain person refuses to support third-party 2-file public domain decoders for MP3/FLAC and Vorbis only needs 1 file. That is too much for that person to handle since they would prefer to understand the formats entirely and would get utterly confused.
3. In that case...forget the whole thing? Or ignore byuu's whining and make a fork in the format? I am willing to do just a monstrocity just to piss him off.

**Comment by qwertymodo** [comment]
You're not just going to piss *him* off, you'll be opening up a gigantic pain in the ass for everyone actually making the hacks that use it.  It's not just about how easy it would be to add a decoder into the emulator, are you going to write an HDL decoder as well so the SD2SNES can support it as well?  Are you going to re-encode all of the existing audio packs out there yourself?  Or are you going to follow up this thread with another profanity-laced rant against the hack authors who won't re-release their work in your new format for you?

**Comment by mudlord** [comment]
1. I wouldnt care about the sd2snes. 
2. Might as well reencode the decent ones anyway.
3. No, I don't hate them enough to rant against them. Theres only a few people that I would wish death on.
