### ISSUE TITLE
Dx11 and Dx12 support.

### ISSUE THREAD

**Issue by PinkLouie** [snes9xgit/snes9x#173]
When I reinstall Windows 10, and try to run Snes9x, it always requires to install Dx9, but it is so old. Can Snes9x do not need DirectX 9 anymore it the future? Use OpenGL by default? Use Dx 11 ou higher? Maybe in the future even Windows will not run Dx9 anymore.

**Comment by OV2** [comment]
S9x does not need any features of newer DirectX versions, and Dx9 can still run on Winxp. So until we drop support for older windows versions this will have to stay this way.

**Comment by jcdenton2k** [comment]
If you play games at all you should know many/most of them still require DX9.  You can blame Microsoft for the complete clustered mess that is the various DirectX versions.

DX9 = compatible with (nearly) every Windows version since WinXP

DX10 = rarely used; only Vista and later

DX11 and DX11.1 = usable on Win7 and later; Win7 requires a Platform Update installed to enable 11.1 support

DX12 = Win10 only

So as it stands, things are still a bit of a mess.

**Comment by bonimy** [comment]
I want start by saying I don't have a lot of experience with DirectX, but I have a keen interest in code flexibility. I'm also a windows 7 user for the record.

It seems Microsoft isn't hosting the June 2008 SDK anymore. A simple Google search of "DirectX SDK June 2008" showed nothing. The End-User Runtimes are available, but the SDK seems to be absent from the Microsoft site. If I am searching incorrectly, then please someone let me know.

If the June 2008 SDK has lost support, then I feel we should upgrade snes9x to the 2010 SDK, which I can verify is still hosted by Microsoft. The only problem is snes9x's dependency on DirectDraw, whose support ended at the 2008 SDK. I'm new to the snes9x project, so I do not know how vital DirectDraw is to it, but it seems we could do without it, as other drawing methods are also implemented.

I did a hack removal of all dependencies on DirectDraw and ddraw.lib and got snes9x to compile against the 2010 SDK. I tested 3D drawing by running A Link to the Past and had no errors. I'll make a quality version when I have the time and make a pull request.

I don't want to get carried away, but I would like to propose that we modernize some of the outdated dependencies, as suggested by @Romain-Piquois in #172. If this sounds okay to users who have more experience working in winXP, then I'll post a new issue to tackle the problems.

Focusing on DirectX in this thread, my proposition would primarily focus on removing retired directX code from snes9x (DirectDraw). It's frustrating that Microsoft had to remove things that we have implemented, but there must have been good reasons, and if the alternatives do exist, it may be wise and beneficial for us to use them, especially if they are already implemented. If we use version-neutral DirectX code, that should close up this issue. And if there are legacy methods we need to keep, then perhaps we can use D3DX_VERSION and D3DX_SDK_VERSION to control them.

**Comment by OV2** [comment]
The only thing needed from the 2008 SDK is ddraw.lib - we could just include this with the sourcecode. That said I have no real problem removing DirectDraw from S9x, I simply left it in since it still works.

**Comment by bonimy** [comment]
I've added Pull Request #183 to remove references to DirectDraw.

**Comment by wingedonezero** [comment]
I do not mean to hijack the thread but i feel like opengl is more future proof wise. I dont feel like adding direct X 11 or 12 support will really add anything special. It would be easier for the developer to focus on one backend that will work on all including linux and mac. Opengl will work on even Xp if you still use that still. Also if he wanted to offer more to people who had newer Os versions. From what i understand vulkan is is very easy to implement from opengl. SInce its basically the direct x 12 version of opengl. Just trying to be constructive.

**Comment by jcdenton2k** [comment]
I would also like to see an OpenGL and/or Vulkan implementation but the issue with Vulkan is that API isn't fully-matured yet.  An example is that it takes ~3k lines of code to draw a single 3D triangle/pyramid.

OpenGL is fully backwards and forwards compatible with nearly everything made in the past 10+ years so it should be nice to have it implemented.  I'm not sure what the linux-based builds use but OpenGL is pretty awesome :)

**Comment by bearoso** [comment]
Vulkan is pointless for a project like this. You see it being used in situations where it can be manipulated to make the hardware accelerated host graphics pipeline more closely mimic the emulated system's pipeline than OpenGL can. For us, we're just using OpenGL as a fast, vsynced blitter. There's nothing to gain from a close-to-the-metal API.

**Comment by OV2** [comment]
All the ports already have an OpenGL implementation. I won't be adding DX11/12 anytime soon, but if someone wants to implement that I have no problem pulling it in.
