### ISSUE TITLE
Phalanx freezes on a black screen

### ISSUE THREAD

**Issue by hugopachecoaz** [snes9xgit/snes9x#206]
I found a problem in Phalanx where shortly after pressing start in the main menu where it says "execute mission", the emulator freezes on a black screen without sound and stops responding altogether, the only way out is to close the snes9x through the task manager. The strange thing is that this does not always happen, just most of the time.
I have tested several ROMs of the same game and the problem persists, both in Retroarch and in the standalone version.
I am using version 1.54.1 x64.

**Comment by kps501** [comment]
Game works as of 2018-05-21! 2018-05-15 fails again. Wow! Snes9x team is really good at fixing stuff! Thank you for making this playable. :)

**Comment by kps501** [comment]
Did some sniffing and sometimes game gets stuck in a nmi wait loop. Forced blank on.

$00/8115 LDA $4210
$00/8118 BMI $FB

$00/811A LDA $4210
$00/811D BPL $FB
*** stuck here

**Comment by kps501** [comment]
I think I get it, maybe.

nmi routine has a cmp $4210 that resets $80 flag. Which prevents $811A from breaking out. Needs longer nmi delay trigger or something?

**Comment by bearoso** [comment]
What it's doing is pretty stupid. It sets the NMI flag at $4200, then uses LDA and BPL to check for vblank via $4210. The problem is that there's a 4 cycle window that LDA has to start in (Snes9x actually incorrectly uses 12), and that window is falling inside BPL's 22 cycles every time. There's no sources of nondeterminism here, so it's sheer luck that it works on the hardware. 

The only other thing I can think of is that the NMI enable bit is being wrongly left enabled here by something buggy in Snes9x, which would give the game programmers more credit.

**Comment by bearoso** [comment]
LDA or BPL could have wrong cycle accounting. If one was 2 cycles longer it would gradually shift the LDA into the correct window.

**Comment by bearoso** [comment]
If we use a delay of 14, it doesn't seem to hit the wrong condition to lock up, so I went with that for now. If that breaks something then we'll revert it. This is susceptible to timing changes, so it's not really a fix, but with Phalanx's tiny programming gaff there isn't really a fix.

**Comment by bearoso** [comment]
And I checked and our LDA and BPL cycle counts are correct.

**Comment by bearoso** [comment]
A jump within the NMI routine should have been 6 cycles longer. Fixed.
