### ISSUE TITLE
-paddev option for the GTK version

### ISSUE THREAD

**Issue by monocasual** [snes9xgit/snes9x#210]
Prelude: congrats on the hard work!

I'm using Snes9x 1.54.1 (Unix version) on a Debian machine, where the USB gamepad has been mysteriously mapped to `/dev/input/js1` (don't ask :rage:). Therefore I have to invoke snes9x with the `-paddev` flag in order to make it work. After that, it works like a charm.

On the GTK version the gamepad doesn't work out of the box, I suppose for the very same reason. Unfortunately I wasn't able to find a way to change the default path to the device. I blindly tried with `snes9x-gtk -paddev1 /dev/input/js1`: the app froze right after the startup.

Is this a missing/unimplemented feature, or is my system poorly configured?

**Comment by bearoso** [comment]
The GTK version uses SDL for joystick support. By default it looks at /dev/input/js1, so that path should be no problem. You could try setting the SDL_JOYSTICK_DEVICE environment variable.

-paddev isn't implemented on GTK, so it tries to load /dev/input/js1 as a ROM image, which obviously doesn't work.

**Comment by nsklaus** [comment]
something is wrong with input on snes9x (both gtk and cli).
first, if i compare with retroarch (which uses snes9x as a core) and with higan too,
they both have no problem finding my bluetooth ps4 controller. 

on snes9x-gtk: it is compltely ignored.
on snes9x (cli) it seems it is not ignored but result is the same.
```
klaus@nsbox:~/Downloads$ snes9x -mute -paddev1 /dev/input/js0 -mute ./smetroid.sfc 
Snes9x 1.55 for unix
Sound buffer size: 12816 (3204 samples)
ERROR: Failed to open sound device /dev/dsp for writing.
	(Try loading snd-pcm-oss module?)
Port 1: Pad #1. Port 2: <none>. 
No ROM file header found.
Unable to find msu file /home/klaus/.snes9x/patch/smetroid.msu1.
Unable to find msu file /home/klaus/.snes9x/patch/smetroid.msu1.
Map_LoROMMap
"Metroid: Redesign" [checksum ok] LoROM, 32Mbits, ROM+RAM+BAT, NTSC, SRAM:64Kbits, ID:____, CRC32:C6EEDA5A
Unable to find msu file /home/klaus/.snes9x/patch/smetroid.msu1.
Using Wireless Controller Motion Sensors (/dev/input/js0) as joystick1
Created XShmImage, size 978944
	Image conversion needed before blit.
Using internal pixel format 555
Unrecognized input device name 'K00:grave': Resource temporarily unavailable
Could not map 'Superscope ToggleTurbo' to 'K00:grave': Resource temporarily unavailable
klaus@nsbox:~/Downloads$ 
```
do you see that part ? 
```
Unrecognized input device name 'K00:grave': Resource temporarily unavailable
Could not map 'Superscope ToggleTurbo' to 'K00:grave': Resource temporarily unavailable
```
i wonder where it does get it from, because i've deleted snes9x.conf from everywhere, in an attempt to get rid of that errror. but it persist. even without any .conf file.

anyway, the result is: i have no idea how to define a proper joystick mapping without the gtk gui.
i'm stuck with snes9x without gamepad.

**Comment by bearoso** [comment]
Coincidentally, I just updated the GTK+ port to use SDL 2.0 for better joystick support. If you compile the git version it'll list the joysticks on the console when you run it.

**Comment by nsklaus** [comment]
@bearoso 
that's a good news. i was trying to compile it but there's errors:
```
./configure: line 5718: AM_GLIB_GNU_GETTEXT: command not found
./configure: line 5942: syntax error near unexpected token `GTK,'
./configure: line 5942: `PKG_CHECK_MODULES(GTK, "$GTK_VERSION")'
```
i'm following this guide: [compiling-snes9x-on-ubuntu](
http://maxolasersquad.blogspot.fr/2013/09/compiling-snes9x-on-ubuntu.html)

would you have any idea what's happening ? or maybe the guide is not good anymore ?

**Comment by bearoso** [comment]
Looks like you're missing gettext or the libglib2.0-dev package.

**Comment by nsklaus** [comment]
thanks for the reply, i have that error but both gettext and libglib2.0-dev are installed

**Comment by bearoso** [comment]
Run ./autogen.sh again if you haven’t after installing those modules. It needs to copy the m4 files into place. Then try configure again.

**Comment by nsklaus** [comment]
@bearoso 
it's working now, bluetooth joystick and all :)
i had a few little other problems but i was able to work my way out.
like: no opengl, no joystick support and such problem at the end of the configure. i had to try and guess which packages needed to be installed. i probably installed few unnecessary things i will need to hunt for  and remove now. it would be nice if, in the doc, the readme, there would be a line or two telling what's needed to compile it out from a vanilla ubuntu/fedora install.
thanks for the help!
now i have a super metroid to play --redesign axeil version-- to be precise :)
