### ISSUE TITLE
[Bug] JoJo no Kimyou na Bouken - garbage characters during intro

### ISSUE THREAD

**Issue by nemo93** [snes9xgit/snes9x#230]
The game does launch no problem. However screen goes full with garbage characters during intro. Just launch the game and wait for the intro. 

Tested on Snes9x 1.53 + 1.54.1 Windows x64 (as well as Snes9x 1.54.1 libretro+RPi).

**Comment by SimpleTease** [comment]
I asked someone to check this since sluffy got C&D and can't comment anymore.

DMA[0]: CPU->PPU Mode:1 0x088000->0x2118 Bytes:2000 (inc) V:181 VRAM: 6000 (1,0) word
BG2: VOffset:0, HOffset:0, W:32, H:32, TS:8, BA:0x7c00, TA:0x6000


snes9x 1.51
$00/91CC A9 01       LDA #$01                A:6080 X:0000 Y:0035 D:0000 DB:00 S:01ED P:eNvMXdizc HC:0828 VC:211 FC:01 I:00
$00/91CE 8D 0B 42    STA $420B  [$00:420B]   A:6001 X:0000 Y:0035 D:0000 DB:00 S:01ED P:envMXdizc HC:0852 VC:211 FC:01 I:00
$00/91D1 60          RTS                     A:6001 X:0000 Y:0035 D:0000 DB:00 S:01ED P:envMXdizc HC:0212 VC:261 FC:01 I:00

bsnes+ 0.73
0091cc lda #$01               A:6080 X:0000 Y:0035 S:01ed D:0000 DB:00 NvMXdizc V:181 H: 894 F:40
0091ce sta $420b     [00420b] A:6001 X:0000 Y:0035 S:01ed D:0000 DB:00 nvMXdizc V:181 H: 910 F:40
0091d1 rts                    A:6001 X:0000 Y:0035 S:01ed D:0000 DB:00 nvMXdizc V:181 H: 940 F:40

**dma
vram starts writing @ dbf1. c000-dbf0 = ignored

0091a5 rts                    A:6001 X:0000 Y:0035 S:01ef D:0000 DB:00 nvMXdizc V:231 H: 304 F:40
00f8ab jsr $f936     [00f936] A:6001 X:0000 Y:0035 S:01f1 D:0000 DB:00 nvMXdizc V:231 H: 346 F:40


Hope this helps

**Comment by kps501** [comment]
JoJo no Kimyou na Bouken (Japan) menu now fixed as of 2018-05-21! 2018-05-15 was still broken. Amazing work devs!
