### ISSUE TITLE
Sound broken sine 1.54 and even in latest test build

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#246]
chester cheetah: wild wild quest
Snes9x 1.54 and 1.54.1 and latest test build.

Sound ok in 1.53 and also ok bsnes/higan and even old zsnes

**Comment by qwertymodo** [comment]
Try re-downloading the test build here https://dl.qwertymodo.com/snes9x.zip it seems to work fine here.  I've only tested through the intro though.  If there is something specific in-game, you'll have to provide more details.

**Comment by jjfmz42015** [comment]
ok this is weird. problem happens on 1.54 and 1.54.1 and on the latest test build at http://www.s9x-w32.de/dl/testbuilds/

However on your version 1.55? its ok. Is this an official release?

**Comment by qwertymodo** [comment]
It's not a release, no.  BearOso just changed the version number strings back in May, so anything built after then will display the new version number.  Looking at those test builds, it seems like the latest was in April.  There haven't been a whole lot of changes since then, so my suspicion would be either the Light Fantasy mapping fix, or else this masking issue in the APU: https://github.com/snes9xgit/snes9x/commit/fe6047213be802cb74cac724a1b83b7263c4dcca

**Comment by jjfmz42015** [comment]
Well I just tested 1.54, 1.54.1 and the April test build again and problem is there but not with this 1.55 so something fixed it!

Is this 1.55 based on the latest code?

**Comment by qwertymodo** [comment]
The file I linked was literally built yesterday, from the code in this repository at that time.  So... yes.

**Comment by roflcopter777** [comment]
So what needs to be done before 1.55 is officially released? Just wondering.

**Comment by jjfmz42015** [comment]
@qwertymodo thank you so much.

Issue solved in next release then! yay!
