### ISSUE TITLE
Can SPC700 emulation be taken to another thread?

### ISSUE THREAD

**Issue by vanfanel** [snes9xgit/snes9x#275]
Hi there,

I was reading the Wikipedia article on the SPC700, and it seems it runs it's own set of instructions, handed over by the main CPU at some given points.
So, wouldn't it be possible to take the SPC700 emulation to it's own thread, thus allowing the OS to send it to another core on low-powered ARM machines with several cores?

I know multithreading in emulation has been deemed as "not appropiate" infinite number of times, but this particular piece of the SNES seems to be well suited.
I would enjoy reading why it's not, if that's the case, as it's a matter of technical curiosity that often comes to my mind.

**Comment by bearoso** [comment]
Nope, they have to be synchronized in case they read the memory mapped registers. Worse yet, multithreading would add non-determinism, which means you have to give up save states.

**Comment by vanfanel** [comment]
Thanks for the response, bearoso!
Is it very often that the main CPU and the SPC700 read the merory mapped registers? I suppose it only happens when the main CPU sends the "audio program" to the SPC700, and then they run independently most of the time (I understand these mapped registers could be simply threated as mutex protected and that's it).

There could be a THREADED_SPC700 #ifdef, for example, and assume the savestates would be lost in that scenario, in favor of better resource usage. Passing -DTHREADED_SPC700 would activate threaded SPC700.. and disable savestates.

**Comment by Romain-Piquois** [comment]
YoyoFr did succeed on the PSP by installing a "mail box" between the audio running on a different CPU and the snes main emulation on another CPU. (A search on google gave me a repositery at https://github.com/173210/snes9xTYL   , ME_SOUND is the macro selecting the build support ME (Media Engine CPU) running the audio thread).

But this code is based on version 1.39 (1.35 ?).
I know at first he had some trouble because of sync between Snes CPU and SPC700 (waiting for signal for transfer...) I think that even Star Ocean did work in the end if I remember correctly. But it should be a build option, making sure that machine having enough horse power in one core do not loose accuracy and keep the simple mono thread logic.
I do not guarantee that such multithread mecanism is as 100% accurate as the current state of Snes9X.

(For the save state, it would indeed require a flag / handshake to make sure both thread are in sync when loading / saving states as bearoso pointed out. But it does not sound like something troublesome either)

**Comment by vanfanel** [comment]
@Romain-Piquois : Thanks for the detailed explanation!
@bearoso : Is it doable? I don't know Snes9x inside well enough, but maybe you could do a new branch for this experiment.

**Comment by bearoso** [comment]
I've added a preliminary commit that threads the APU processors. 

It basically offloads the end-of-scanline catch-up process to a thread. Then, if during the next scanline it needs to synchronize, it'll wait and do so. So, while synchronization-heavy or sound streaming games will still work exactly the same, they won't benefit as much, or may suffer a overhead penalty. It might be better to accumulate some time for multiple scanlines before dispatching a thread to eliminate some overhead during normal games.

As of now, there's a pthread implementation. That means no Windows support yet. I'm totally unfamiliar with Windows threading, so that might be up to someone else. It's only a matter of replacing the top 5 functions with their Windows equivalents and sectioning it off with some #ifdef _WIN32.

**Comment by bearoso** [comment]
Well, experiment tried, and it failed. The overhead is too great. It can be done, but it's slower than a non-threaded version. On Linux, we lose about 30% performance, no matter the synchronization method. On Windows, if I loosen the synchronization, I can get about a 5% speed improvement, but we don't really need the improvement on Windows.

**Comment by vanfanel** [comment]
@bearoso : Thanks for trying. I have built the GNU/Linux version on ARM (Rpi3) as a RetroArch core, and indeed it doesn't seem any faster than the "non-threaded" version. Not any slower, either. I built it with -DUSE_THREADS and the usual Rpi3 CFLAGS, but it made no difference, for good or bad.

**Comment by bearoso** [comment]
You have to stick
`Settings.ThreadedAPU = TRUE;`
Before the S9xInitAPU call to enable it. Performance will probably be worse.

**Comment by vanfanel** [comment]
@bearoso : I have built a new core with that option on libretro.cpp before the mentioned call, I'd say performance is still the same. Oh well :(

**Comment by bearoso** [comment]
Well, the changes are always in the tree to bring back if I get a clever idea or something to make it faster.
