### ISSUE TITLE
Slayers continue freeze

### ISSUE THREAD

**Issue by SimpleTease** [snes9xgit/snes9x#296]
When loading a save game through menus, game freezes.

Apparently that "Canoe guy" found a hack to play this game. Is there a way to fix this in snes9x? Some vague jabber about nmi, slow fastrom or something.

**Comment by bearoso** [comment]
He says an interrupt is firing during the load routine because our timings are bad. This isn't so much a bug as a general deficiency of Snes9x. 

He disables interrupts at  83/a49d to get around it. Just need to debug to know whether it's intended to occur before or after the load routine. Then we find what's too slow or too fast.
