### ISSUE TITLE
Air Strike Patrol - interlace fixed, random crash after Marko + SGNG fix

### ISSUE THREAD

**Issue by kps501** [snes9xgit/snes9x#318]
This one's been around for awhile. Start new game. Skip briefing 1. On radar area maps, pause emulator (single step frame). Minimize window. Restore window. If no garbage, single step frame and minimize - restore. You should now see some weird mini-map on top of the screen.

It switches mid-frame from 512 to interlace 512. memmove doesn't copy correctly but I think this one does.

gfx.cpp
				for (register int32 y = (int32) GFX.StartY - 2; y >= 0; y--)
					memmove (GFX.Screen + (y+1) * GFX.PPL,
							 GFX.Screen + (y+0) * GFX.RealPPL,
							 GFX.Pitch*sizeof(uint16));

**Comment by bearoso** [comment]
@kps501, are you seeing lockups on Air Strike Patrol?

**Comment by kps501** [comment]
No lockups. Just some strange visual junk when you pause the emulator, minimize and restore window. On the area radar briefing screen.

**Comment by bearoso** [comment]
I'm definitely getting lockups after 85b0cf01919d254ec4a7c5fa919b474cbfa2c3f4.

**Comment by kps501** [comment]
Same here. Just noticed it, that commit.

**Comment by bearoso** [comment]
@OV2 any ideas? After reading more of anomie's and byuu's stuff, I removed the IRQTransition thing, because I think that's wrong. I also corrected a misinterpretation I had about vtimers, so I believe everything we're doing now is correct.

The behavior Marko expects is seemingly the reason ASP breaks. Marko wants CLI to not update the IRQ mask flag until after the next IRQ check, which is definitely the correct behavior. 

ASP does a CLI then SEI, which briefly unmasks the IRQ to trigger it, which seemingly works as far as my traces are concerned. The SEI then remasks it. I made a fix here where while the check for the IRQ flag at the end of SEI doesn't use SEI's result, it is still updated in time to be stored in the stack.

**Comment by bearoso** [comment]
And I just noticed the SNES test program character test is broken.

**Comment by OV2** [comment]
I'll try to take a look at ASP. I think the IRQTransition in the old variant was a way to simulate the cycle-delay between the counters being reached and the irq firing.

The character test was fixed by the openbus changes? I haven't really looked at how those work at all...

**Comment by bearoso** [comment]
Yeah, the Funaki blah blah wrestler fix wasn't correct, and that fixed the character test. I still have to change back the other PPU.OpenBus1 to OpenBus. 

> I'll try to take a look at ASP. I think the IRQTransition in the old variant was a way to simulate the cycle-delay between the counters being reached and the irq firing.

My earlier understanding was that the timer fires, and the check to bring the IRQLine low occurs on the last cycle of an instruction, then the next instruction's last cycle checks IRQLine and the IRQ flag. 
My current understanding is that the last cycle of an instruction checks the timer and brings the IRQ line low, and we can immediately trigger an IRQ as long as the IRQ flag is clear. I believe this is actually correct.

**Comment by OV2** [comment]
This seems to have fixed the lockup for me. IRQ flag was reset immediately after NMI start, which in turn immediately triggered an IRQ.

**Comment by bearoso** [comment]
Ah, yes. The value pushed to the stack during the NMI should also be the new value. Good spot.

**Comment by bearoso** [comment]
This should be fixed now.
