### ISSUE TITLE
Commercial Licensing

### ISSUE THREAD

**Issue by tomspilman** [snes9xgit/snes9x#336]
Hi.

I have an indie game studio and recently we've been doing ports for various companies. 
 
I've been approached about some ports of old SNES titles to main stream consoles (PS4, XB1, etc).  We're evaluating the possibility of licensing the core of an existing SNES emulator so we can port it to consoles and ship one or more titles.

Does the SNES9x team have a process for doing this?  Has this been done before?  If the cost of licensing is reasonable this could be a win for the copyright holders and the project as we submit fixes and improvements back.

However i understand the complexity of this sort of thing, so i know it may not be possible at all too.

Thanks!

**Comment by bearoso** [comment]
Snes9x is strictly non-commercial, and at this point the number of contributors has made use under any other license impossible. 

byuu at byuu.org is licensing out higan/bsnes for commercial use. His new bsnes core may provide enough performance to be suitable for your needs. Though you may have trouble contacting him because he'll be overseas for the next couple weeks.

**Comment by tomspilman** [comment]
Thanks @bearoso !

**Comment by vince94** [comment]
This issue is closed but I just want to say, @tomspilman thank you for inquiring about this! The recent thing with the Chrono Trigger PC port of the mobile port with the weird touchscreen UI left a lot to be desired, but it sounds like whatever company you work for wants to put in the effort to make sure stuff is re-released as accurately as possible! :+1:
