### ISSUE TITLE
Bug: Pilotwings (USA, Japan)

### ISSUE THREAD

**Issue by ramtrooper** [snes9xgit/snes9x#381]
If you let the game play its demos for awhile, you'll get to watch the plane landing. But it crashes in the field instead of the runway.

**Comment by bearoso** [comment]
Probably related to the simulated DSP.

**Comment by retrotalker** [comment]
DSP1.Op28R = ((Node2 - Node1) * (C & 0x1ff) >> 9) + Node1;

#if 0
if (DSP1.chipset == DSP1)
{
    if (Pos & 1) DSP1.Op28R -= (Node2 - Node1);
}
#endif

DSP1.Op28R >>= (E >> 1);


I don't know how to integrate this but it fixes Pilotwings demo. Now I wonder a bit about Mario Kart since byuu says it first shipped with 1 and later 1B but same rom. ^^

**Comment by bearoso** [comment]
Pilotwings apparently also shipped with a DSP-1B, with the plane crashing a known bug. For now, we'll go with no fix, and if we switch over to LLE in the future we'll revisit it.

**Comment by ramtrooper** [comment]
That's fair! Thanks guys for looking into it. It's a really minor thing and honestly I hope someone just fixes the game to playback demo correctly with 1B chip.
