### ISSUE TITLE
reduce input lag?

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#383]
reduce input lag in d3d mode is doing something but not in ogl or dd mode. is this expected?

**Comment by OV2** [comment]
It does nothing in DirectDraw, in OpenGL it will call glFinish after every frame.

**Comment by jjfmz42015** [comment]
on my system with it on in d3d in 4k resolution i get slowdowns but not in open gl. also running emu at max speed with it on or off in ogl no diff but d3d lower top max speed.

**Comment by bearoso** [comment]
In D3D, the trick is to lock the backbuffer, which forces all buffers to be coherent. It might be more performant on some drivers to use D3DLOCK_DISCARD instead of D3DLOCK_READONLY.

If you've got drivers that are forcing triple buffering in OpenGL, the glFinish trick won't work. We could use fences, but that's a little more complicated.

**Comment by jjfmz42015** [comment]
thanks for explaining
