### ISSUE TITLE
bug: loadstate sound channels

### ISSUE THREAD

**Issue by ramtrooper** [snes9xgit/snes9x#384]
I think this only affects libretro port?

Load game.
Options - turn off all sound channels. Save state.
Options - turn on all sound channels. Load state.
No sound. Change random option. Sound.

**Comment by bearoso** [comment]
Snes9x stores which channels are activated in the save state. When the libretro port is notified of a setting change (any change), it resets all options to what it has them stored as.

I don't think this is a bug, just expected behavior. What would be an alternative behavior that wouldn't upset some party or another?

**Comment by ramtrooper** [comment]
I guess a libretro toggle could work:
use global sound channels on load state
or
reset sound channels on load state


Then it only affects libretro.cpp. But using the saved channels makes sense too (expected behavior).

Thanks for considering this further.

**Comment by ramtrooper** [comment]
Admittedly this doesn't bother me all that much.
