### ISSUE TITLE
SuperFX speed is too slow

### ISSUE THREAD

**Issue by jjfmz42015** [snes9xgit/snes9x#407]
in 1.56.2-365 course selection garbage graphics fixed, but now when you press start the window it opens flickers like mad

**Comment by bearoso** [comment]
That's not new, it's been there forever.

**Comment by jjfmz42015** [comment]
is there a reason sfx is being run slower? I mean im sure there is Im just curious is there a game known to need this slowdown in snes9x?

**Comment by bearoso** [comment]
I don't know. It was before my time. Presumably it was roughly the right speed for Star Fox to run at.

**Comment by bearoso** [comment]
I increased the speed just enough to get rid of the stunt race bug. 

I'm not sure if Star Fox is too fast now, but I'm not going to dig out my cartridge to check. Comparing with higan is also a dead-end, because higan runs the SuperFX too slowly as well.

**Comment by Nashismo** [comment]
> 
> 
> I increased the speed just enough to get rid of the stunt race bug.
> 
> I'm not sure if Star Fox is too fast now, but I'm not going to dig out my cartridge to check. Comparing with higan is also a dead-end, because higan runs the SuperFX too slowly as well.

Yes Star Fox is too fast. I made a complete analysis of the Snes cart/Snes real hardware and Snes9x on Wii and is very much faster, you can read my conversation with the developers of Snes9x port here:

https://github.com/dborth/snes9xgx/issues/832

Thank you for listening.

**Comment by bearoso** [comment]
@Nashismo, @dborth, We increased the default speed and provided the overclock option at the same time. My intention was that it was also for underclocking so people could hand-tune the speed, i.e. to make Star Fox slower. The Snes9x overclock variable works at less than 100% in order to underclock, so I'd just expand your overclocking option with the lower range.

As it is now, no emulator does this chip at a correct speed because it has so many complexities regarding performance. bsnes/higan is closest, but there's still something missing regarding the pipelining, so even it gets things wrong.

**Comment by jjfmz42015** [comment]
I like how sfx is currently handled on snes9x.

**Comment by bearoso** [comment]
What I don't like is that there's no one correct speed. See issue #522 for our discussion about Yoshi's Island. The clock speed that gets one part right is always way off on another part. We'd have to write an entirely new SFX module to fix that, and we still don't know every intricacy about the chip.

**Comment by Nashismo** [comment]
Exactly. Games like Star Fox run much slower on original hardware. Making the game playable.

@jjfmz42015  The speed you see is not accurate and does not represent what the original developers intended for these games.

Is not about making the games work at slower framerate, is about making the game work at the correct speed. Something completely different.

**Comment by jjfmz42015** [comment]
I understand. However based on what other emulators are doing i find snes9x to handle it good. Now if someone could rewrite sfx emu to be perfect that would be amazing im not doubting this. Im just happy with current snes9x in the Sense that all the sfx games are "playable"

**Comment by Nashismo** [comment]
> 
> 
> I understand. However based on what other emulators are doing i find snes9x to handle it good. Now if someone could rewrite sfx emu to be perfect that would be amazing im not doubting this. Im just happy with current snes9x in the Sense that all the sfx games are "playable"

I am happy too of how good and lightweight Snes9x is, it has always been good in this regard. but sometimes people simply don't see how inaccurate FX chip emulation is, because they don't experience the original cart/console, they think it runs perfect but it does not.

Higan has reached great levels of accuracy, but you require a beefy PC in order to do this. 

By the way, I was checking some videos on the Super Snes Mini and it seems to handle the timing of Star Fox pretty accurately. Well that's Nintendo emulator, but I guess it wouldn't hurt to try and figure out how they made that possible (remembering that the snes mini is pretty much a raspberry pie in terms of hardware speed).

**Comment by bearoso** [comment]
The SNES Mini doesn't get it correct, either, and it uses game-specific "profiles". There's nothing they know that we don't, and what we don't know could already be lost to the ether forever.

We could reduce the default speed to match it easily, but I don't like the idea of introducing new game-specific hacks.

**Comment by Nashismo** [comment]
> 
> 
> The SNES Mini doesn't get it correct, either, and it uses game-specific "profiles". There's nothing they know that we don't, and what we don't know could already be lost to the ether forever.
> 
> We could reduce the default speed to match it easily, but I don't like the idea of introducing new game-specific hacks.

I understand, and it is true, the Snes Mini doesn't get the timing correct either, better, but still missed the mark.
It is great your way of thinking and I think all fans of this emu, we all appreciate that, hacks suck, pretty much everyone agrees, is a short term fix that does not help on anything long term. We only need to remember PCX2... I don't want to remember that! :)

Cheers and thanks again.

**Comment by Nashismo** [comment]
> 
> 
> The SNES Mini doesn't get it correct, either, and it uses game-specific "profiles". There's nothing they know that we don't, and what we don't know could already be lost to the ether forever.
> 
> We could reduce the default speed to match it easily, but I don't like the idea of introducing new game-specific hacks.

@bearoso Still, and I forgot to ask you, if you could introduce an underclocking options it would be nice so that everyone could tweak aound at their hearts desire.

But I believe you already said you would work on it? I am sorry I am sleepy. It would still be nice to have the "option" there, even if it is a bit hacky.

**Comment by bearoso** [comment]
It’s already there on the Windows and Gtk ports, you can go below 100. dborth just needs to expand the range to go below 100 to underclock on Snes9x GX.

**Comment by Nashismo** [comment]
> 
> 
> It’s already there on the Windows and Gtk ports, you can go below 100. dborth just needs to expand the range to go below 100 to underclock on Snes9x GX.

Ok. Thanks bearoso.
