### ISSUE TITLE
Condense copyrights.

### ISSUE THREAD

**Issue by bearoso** [snes9xgit/snes9x#450]
With how much a hassle it is to update the copyright data, I think it might be good to replace the complete copyright that's included at the top of nearly every file with a non-aging stub that just points to a whole file in the docs directory. It would be much simpler.

**Comment by qwertymodo** [comment]
I think the previous thread actually makes a good argument *for* doing exactly this, but instead of putting it in the docs folder, I would put it into the root LICENSE file.  A lot of times people will just look at the root LICENSE file and nothing else.  I would also put a reference to the fact that the project contains components licensed under the LGPL and specify exactly which components those are, but leave the full LGPL license text as a separate document.

**Comment by bearoso** [comment]
Ok, for the stub, how about this:
```
/* Snes9x - This file is licensed under the Snes9x License.
   For further information, consult the LICENSE file in the root directory. */
```

**Comment by bearoso** [comment]
Or maybe something like this to be more consistent with what we have now:
```
/*****************************************************************************\
*  Snes9x - Portable Super Nintendo Entertainment System (TM) emulator.       *
*   This file is licensed under the Snes9x License.                           *
*   For futher information, consult the LICENSE file in the root directory.   *
\*****************************************************************************/
```

**Comment by bearoso** [comment]
I like it centered:
```
/*****************************************************************************\
     Snes9x - Portable Super Nintendo Entertainment System (TM) emulator.
                This file is licensed under the Snes9x License.
   For further information, consult the LICENSE file in the root directory.
\*****************************************************************************/
```
