### ISSUE TITLE
Movies not working...

### ISSUE THREAD

**Issue by JoseMHC** [snes9xgit/snes9x#458]
So, after recording a .smv movie, I then proceed to play it, and even though the recorded input shows in the input display, it doesn't actually do anything (and it's like there's no movie at all; I can still press buttons myself to do stuff)

Could it be settings-related? I don't find anything that could be causing this...

**Comment by OV2** [comment]
It's not settings related, it doesn't work since 1.56.

@bearoso it's a result of the change when the main loop exits. The movie playback restores input in S9xControlEOF (inside S9xEndScreenRefresh), after this the main loop exits and input can be overridden by the port reporting. If I make sure this does not happen in the win port when a movie plays it works again. I'll have to take a closer look at that.

**Comment by bearoso** [comment]
It's still playing inputs in the GTK+ port, but they're overwritable. Well, we now know for sure that the input lag fix had an effect.

Moving S9xMovieUpdate to the start of the next loop is probably the best option.

**Comment by bearoso** [comment]
See if commit bb66278 works.
