### ISSUE TITLE
SA1 code question

### ISSUE THREAD

**Issue by bladeoner** [snes9xgit/snes9x#479]
@bearoso I got a question about the "Reduced version of Vitor's fix for SA1 speed throttle." commit.

I backported this to Snes9x GX (Wii) and the results are really good, especially Jikkyou Oshaberi Parodius, which has between 48 and 54 FPS and now between 58 and 60 FPS.

But there are two games which have less FPS now:
Super Mario RPG
Kirby's Dreamland 3

In the code before the commit we had the following line (**129**) in **sa1cpu.cpp** where in the past the value of 5 was 3 and in Snes9x GX we could play with the value in the form of a hack to get games the correct FPS:
**for (int i = 0; i < 5 && !(Memory.FillRAM[0x2200] & 0x60); i++)**

After the commit we have the following lines (**129**) in **sa1cpu.cpp**:
#undef CPU
int cycles = CPU.Cycles * 3;
#define CPU SA1

for (; SA1.Cycles < cycles && !(Memory.FillRAM[0x2200] & 0x60);)

My question is if I want to reduce the speed what should I adjust, I'm a little bit confused because the Memspeed is also changed from SLOW_ONE_CYCLE to ONE_CYCLE.

What I tried is this:
#undef CPU
int cycles = CPU.Cycles * NAME;
#define CPU SA1

for (; SA1.Cycles < cycles && !(Memory.FillRAM[0x2200] & 0x60);)

And then define **NAME** under Timings in **Snes9x.h**:
**int32	NAME;

And define **NAME** in **Memmap.cpp**:
		if (match_id("AFJJ") || match_id("AFJE")) { // Kirby's Dream Land 3
			Timings.NAME = 1;
		}
		else {
			Timings.NAME = 3;
		}**

With the old code this worked but now it doesn't seem to have any effect anymore.

I hope you can point me in the right direction.

Thanks in advance.

**Comment by bladeoner** [comment]
@bearoso Before commit "Reduced version of Vitor's fix for SA1 speed throttle." both games ran to fast so what you are saying is true 1.56-1.58 was too fast, so to fix that we changed the following:
Original code: for (int i = 0; i < 5 && !(Memory.FillRAM[0x2200] & 0x60); i++)
Adjusted code: for (int i = 0; i < 3 && !(Memory.FillRAM[0x2200] & 0x60); i++)

With the adjusted value Super Mario RPG is working 60 FPS in the more emulator intense spots.

Now after the commit the frames drop so it looks like the game is too slow, same goes for Kirby's Dreamland 3. In November 2018 we updated the core from 1.53 to 1.57 in Snes9x GX (Wii) and recently to 1.58 since November Kirby's Dreamland 3 was performing really bad so I think it was already running too slow. But Super Mario RPG we could fix.

I will try to increase the Timings.NAME = 1; to Timings.NAME = 5; see how that goes.

I will let you know how it goes.

**Comment by bladeoner** [comment]
Tried the 5 setting but it gives the same result.

**Comment by bearoso** [comment]
What you're saying is that emulator performance is dipping because of the new code. In that case, modifying that value isn't going to change anything. I believe that because we're now executing the SA1 for cycles that the SCPU was in DMA that it increased the performance requirement. We're simply calling into the SA1 code more often.

Try out commit 3dbac11 and see if it improves things.

**Comment by bladeoner** [comment]
@bearoso tested the commit it has a negative impact on the performance, the FPS drops a little bit more with this change.

**Comment by bearoso** [comment]
Ok, then it may just be that the Wii doesn't have the power to run the SA1 enough to be at the correct speed. If the old change (3 -> 5 opcodes) already produced a FPS loss, then you're at the threshold of 100% CPU usage. You can obviously keep the old SA1 timing if you want, but that's not an ideal method, either. The problem with 3 opcodes per S-CPU opcode is that the actual emulated game runs too slowly because the SA1 isn't given enough relative runtime. You can see this in the butterflies in the opening and in Geno's multitarget attacks.

**Comment by bladeoner** [comment]
I think you are right, the hardware is really limited, when implementing core 1.58 we had to leave out the APU that was introduced in 1.54 so you can imagine.

For now it's fine to keep the SA1 commit but better not to apply 3dbac11

**Comment by bladeoner** [comment]
@bearoso I wanted to inform you I fixed the issue by creating a hack to reduce the Settings.OneClockCycle speed from 6 to 8. Thank you for your help
