### ISSUE TITLE
A.S.P. Air Strike Patrol issue

### ISSUE THREAD

**Issue by lordpeluca** [snes9xgit/snes9x#524]
In the A.S.P. Air Strike Patrol, a flashing horizontal line appears from time to time.

Trying the game with higan and a so-called "snesgt" the problem disappears.
https://i.postimg.cc/02dSZfsr/f1.jpg

Snes9x 1.59.2.

I seem to remember that in other versions it didn't happen.

**Comment by bearoso** [comment]
When the shadow is over the direct middle of the screen, the whole scanline darkens. That's the best compromise, because the shadow moves back and forth. I changed the point which Snes9x grabs the PPU state to the exact middle of the screen because other games had graphics glitches. On higan it shows the shadow properly (except the brightness is analog and changes slowly enough to make it really hazy on a real SNES). On SnesGT it omits it entirely. This is one of those you'll need to use higan for.

**Comment by lordpeluca** [comment]
I see, changes were made. The game doesn't really take my sleep away, I reported it only because the problem of the long blinking horizontal line I didn't see it in another version, like for example in the Snes9x v 1.56.

Thank you very much for answering :)

**Comment by jjfmz42015** [comment]
this is due to line rendering rather than dot rendering in ppu. if the rendered line caught the shadow the whole line is grey. Expected from a line render ppu. Unless they program a game specific fix to ignore rendering shadow.

**Comment by jjfmz42015** [comment]
Hmmm tried older versions sure enough shadow line doesnt appear. seems older builds ran this better.

**Comment by bearoso** [comment]
> Hmmm tried older versions sure enough shadow line doesnt appear. seems older builds ran this better.

It's deliberate. Moving the PPU snapshot location to the middle fixed other games. Don't play this game with Snes9x.

**Comment by jjfmz42015** [comment]
> 
> 
> > Hmmm tried older versions sure enough shadow line doesnt appear. seems older builds ran this better.
> 
> It's deliberate. Moving the PPU snapshot location to the middle fixed other games. Don't play this game with Snes9x.

I see.


Thanks for the verification.

**Comment by jjfmz42015** [comment]
Hey in a case like this since we know what the fix could be for grey line shouldn't a game specific hack be made just to make the emulator compatible to one more title in the library? I mean I'm not a fan of hacks but considering the line ppu will never run this game without that mod the game specific hack would just raise playable games amount. Not that it matters to me I can play asp 4 other ways. Just a fan of snes9x and sharing thoughts

**Comment by lordpeluca** [comment]
The solution of the game "Sugoro Quest+++++ - Dicenics (Japan)" of this thread:
https://github.com/snes9xgit/snes9x/issues/595

It seems to solve the problems of the game "A.S.P. Air Strike Patrol" that were discussed in these two threads:
https://github.com/snes9xgit/snes9x/issues/524
https://github.com/snes9xgit/snes9x/issues/561

Here are some photos that show that the bugs are fixed:
https://i.postimg.cc/PxB9d4GC/F1.jpg
https://i.postimg.cc/T1fjjLgk/F2.jpg

So I think you should close them in my humble opinion. Or at least close mine.

Greetings and thank you very much!

**Comment by bearoso** [comment]
This was fixed because a hack was added as described above to move the snapshot of the PPU state specifically when this game was run. It's still not "fixed" in the strict sense because the shadow doesn't show up.

**Comment by lordpeluca** [comment]
Yeah, I know that. To see the shadow of the plane the option is higan.

But at least the error of the long blinking horizontal line was solved. That's what I mean, :)

Greetings.
