### ISSUE TITLE
Savestate save/load preview

### ISSUE THREAD

**Issue by OV2** [snes9xgit/snes9x#580]
I've added as simple dialog to the win port (win32-saveload-preview branch) that displays the screenshots contained in the savestates on buttons. Works ok, but requires some shenanigans at the moment since I need to load the states to get to the images.

![Sample image](https://i.imgur.com/ZpRR51c.png)

Any feedback is appreciated.

**Comment by OV2** [comment]
I've simply merged this for now with additional hotkeys for the dialog. Maybe the next version will bring some feedback :)

**Comment by xZabuzax** [comment]
Hey I can gladly do some testing for you on this feature and even provide some new ideas to help improve it.

Bear in mind that I'm not a coder nor a graphic designer, I'm simply a guy that is very passionate on these type of features.

**Comment by xZabuzax** [comment]
This new feature is looking promising so far. This new Save/Load window is not the GUI I had in mind, this is more like a popup window but it's still good nonetheless.

I did find an annoying issue with it, I'm sure you are aware of it. If you are in full-screen and open the popup Save/Load window it won't appear, it will be invisible even though it's there, for it to be visible in full-screen you need to hit "Escape" first to show the emulator menu on top of the screen, once the emulator menu is visible then you can open the popup Save/Load window and this time it will be visible in full-screen.

**Comment by OV2** [comment]
I only saw this problem in OpenGL, I've pushed a fix that fixed it for me.
The "P" should now be capitalized.

**Comment by xZabuzax** [comment]
> I only saw this problem in OpenGL, I've pushed a fix that fixed it for me.
> The "P" should now be capitalized.

Awesome, I'm glad it got fixed, yeah I was indeed using OpenGL. Can you please provide a build with that issue fixed? I want to use that build as my default Snes emulator. Once this feature is implemented in the next version of Snes9x then I'll use that one.

**Comment by OV2** [comment]
You can always get the newest build here: https://ci.appveyor.com/project/snes9x/snes9x
Click on the platform and build you want, then on artifacts, and you will get the link.

Here is the current version: https://ci.appveyor.com/api/buildjobs/v0uis4sbhbsvjame/artifacts/snes9x-1.60-171-g89f4802-win32-x64.zip

**Comment by xZabuzax** [comment]
> You can always get the newest build here: https://ci.appveyor.com/project/snes9x/snes9x
> Click on the platform and build you want, then on artifacts, and you will get the link.
> 
> Here is the current version: https://ci.appveyor.com/api/buildjobs/v0uis4sbhbsvjame/artifacts/snes9x-1.60-171-g89f4802-win32-x64.zip

Thanks mate, I had no idea those builds were there, that link is somewhat "hidden" so a lot of regular users like me wouldn't have known about it.

If I find another bug I'll let you know. That being said, I can still provide ideas to improve that feature:

*It would be nice having that Save/Load window interact with the keyboard as well, for example, assign those slots a specific number (from 1 to 0) and when you press those numbers it will also save or load that specific slot, so if you have it open and press in your keyboard the #2 then it will either save or load that #2 slot.

*Another thing that can improve it is having that Save/Load window show you the last Save State visually (like having a yellow border around it just like Snes9x for Mac/Os X), this way you can find the last Save State easily without having to look at the dates one by one.

*Another thing that can improve it is being able to choose those Save/Load slots by moving it with the arrow keys or a pad, this way the people using a controller can open that Save/Load window and choose a specific slot to Save or Load without having to use the keyboard or the mouse. I'm a keyboard guy, I don't use a pad but people using pads will definitely find this one useful.

Anyway, I'm not asking to implement those features, those are just some ideas that you can take into consideration and implement it when you feel like it, I'm already satisfied with how that Save/Load window turned out to be.
