### ISSUE TITLE
Snes9x wasting a frame somewhere?

### ISSUE THREAD

**Issue by Tatsuya79** [snes9xgit/snes9x#584]
[While doing some latency tests to show to Byuu for bsnes, recording both executables side by side and making Mario jump in smw, I did notice that:](https://github.com/byuu/bsnes/issues/52#issuecomment-537317297)

-in RetroArch snes9x is reacting a frame earlier than bsnes (RA)
-snes9x stand-alone is similar to bsnes stand-alone
-snes9x core in RA is reacting a frame earlier than bsnes stand-alone

This was in windows7, no RA advanced sync method used, gsync off, aero off.
@realnc [had the same outcome on Linux as well.](https://forums.libretro.com/t/bsnes-hd-input-delay/24422/9)

Is the "Reduce input lag" option not working or something else?
edit: I recorded with it off, and bsnes then reacted faster 17 times out of 25. So it seems to be working.

**Comment by bearoso** [comment]
Snes9x-win32 prioritizes the GUI, so I can see why this happening there. Direct3D with the "Reduce input lag" option also may not work as well as it's up to driver implementation. 

I guarantee the GTK+ port with one of the reduce input lag options _will_ perform optimally, comparable to RetroArch with hard sync 0. 

So the problem seems to be bsnes itself having additional latency. The "lag fix" that was applied long ago was simply popping out of the SNES frame at a different location, before the first rendered line instead of before NMI. The sampling location is probably the problem here with bsnes.

**Comment by Tatsuya79** [comment]
Ok, so you know what that's about.
Just wanted to give that feedback in case anything was missed there.

I'll close this.
