### ISSUE TITLE
macOS Big Sur support / missing info

### ISSUE THREAD

**Issue by wisteso** [snes9xgit/snes9x#699]
I think? I've searched every page of this github project and snes9x.com without luck.  I've found CI builds but those only cover Windows.   The releases page only covers 1.60 from back in 2019 and only 32 bit for macOS, and I'm not seeing any nightly builds.

If there is an 64 bit macOS build somewhere, it's really hard to find and maybe that's the root issue.  Otherwise, I'm sure others are coming here wondering the same thing and maybe someone knows the state of Big Sur support.

Thank you!

**Comment by MichaelBuckley** [comment]
There are 64-bit builds linked in #586, the latest was posted on September 7th. They work with Big Sur, and are even universal Intel/M1.

The big reasons they haven't been put on the releases page is because there hasn't been a full release Snes9x on any platform since 1.60, and the Mac port isn't back up to where the 32-bit version was, though most games can be played. For more information on why it's taken so long, see https://buckleyisms.com/blog/snes9x-on-macos-catalina

Also, strangely, since the pandemic started, I've had less free time to work on side projects, which has slowed the pace of development. I did get mouse/super scope/justifier support working, but I need to fix up a couple things before doing another build.

**Comment by keithbowes** [comment]
It is weird that Snes9x is still on 1.60.  I mean, there are only sporadic commits, but that has amounted to nearly 300 commits over the past two years, which seems substantial.

**Comment by alexanderguryev** [comment]
I've tried out several of the builds linked above on 11.6.1 on a 2016 MBP 15" and the app only displays a small black window when loading any rom.

**Comment by MichaelBuckley** [comment]
@alexanderguryev Please give this build a try. It contains a fix that didn't make it into the last build, but has been in the git repo for a little bit. It fixed a similar issue on a computer with a malfunctioning discrete GPU, but I have only tested it on that one machine.

Please also do not use closed bugs to report issues. You can either use #586 or open a new issue. Thanks.

[Snes9x.app.zip](https://github.com/snes9xgit/snes9x/files/7902044/Snes9x.app.zip)

**Comment by alexanderguryev** [comment]
This one just crashes when loading any rom file.

**Comment by MichaelBuckley** [comment]
Could you attach a crash report? You can find them in /Applications/Utilities/Console.app. There's a "Crash Reports" section in the sidebar.  You can right-click or control-click on a crash report and choose "Reveal in Finder" to get the file. Thanks.

**Comment by alexanderguryev** [comment]
Here you go:

[crashes.zip](https://github.com/snes9xgit/snes9x/files/7902254/crashes.zip)

**Comment by MichaelBuckley** [comment]
Unfortunately, this is crashing in video driver code.

The only change between this build and the latest build in #586 is that it's always using the integrated GPU instead of the discrete GPU. (Some MPB models have two GPUs, a low-powered integrated GPU, and a higher-powered discrete GPU). Both GPUs have different video drivers.

I'm not sure if I'll be able to work around this one. This is definitely either a bug in the OS's video driver or a hardware problem with the GPU, and I'm not able to reproduce it on my 13-inch MBP, so I can't be sure if any change I make will fix it, but I will ask some people who have helped me with Metal rendering code in the past if they have any ideas.

**Comment by eisnerguy1** [comment]
Your build from [November 15th, 2021](https://github.com/snes9xgit/snes9x/issues/586#issuecomment-969438854) is the only recent build that I can get to actually run any rom. I'm not sure what happened after that build that caused it to break. I also tried the latest [Master build](http://cirrus-ci.com/task/6752294652870656) and the same issue is present. Thank you for all of your hard work in getting Snes9x updated 😄 Back to playing more Star Fox 2 😄 
![Star Fox 2 (USA) 002](https://user-images.githubusercontent.com/3295271/150976851-f251cff7-028e-4444-be16-aa30f9a77056.png)

**Comment by MichaelBuckley** [comment]
That's the second report now of someone having issues with the change to always use the integrated GPU. I guess I'll have to revert it and make it an option in preferences.

**Comment by ademirml** [comment]
> @alexanderguryev Please give this build a try. It contains a fix that didn't make it into the last build, but has been in the git repo for a little bit. It fixed a similar issue on a computer with a malfunctioning discrete GPU, but I have only tested it on that one machine.
> 
> Please also do not use closed bugs to report issues. You can either use #586 or open a new issue. Thanks.
> 
> [Snes9x.app.zip](https://github.com/snes9xgit/snes9x/files/7902044/Snes9x.app.zip)

Hey man, it worked. Thanks. However, the fast forward mode is toggle ON/OFF, there is no option to change it to ON while holding the key and OFF while not holding. Is there another newer version where this option was included?
