### ISSUE TITLE
macOS 64 bit version

### ISSUE THREAD

**Issue by jonasw8** [snes9xgit/snes9x#713]
Good Night!

Its possible create a version for macOS 64 bit ? macOS Catalina and macOS Big Sur need 64 bit only

Att

Jonas Wander

**Comment by MichaelBuckley** [comment]
Hi, there is already a ticket for this, #586, with builds that run on Catalina and Big Sur. Scroll down near the bottom of the thread to find the latest build.

Because the UI was written in Carbon, which did not make the transition to 64-bit, so it had to be rewritten in Cocoa. As a result, a lot of features aren't yet available, and while I'm working on implemeting them, I've had very little time since the start of the pandemic.
