### ISSUE TITLE
Frame advance hotkey stops working after about 25 days of Windows uptime

### ISSUE THREAD

**Issue by Fernap** [snes9xgit/snes9x#716]
Just as the title says.  You can still advance via the menu, but the hotkey isn't recognized.  This appears to stem from [line 947 in win32/wsnes9x.cpp](https://github.com/snes9xgit/snes9x/blob/master/win32/wsnes9x.cpp#L947).  The cast to `int` is causing a signed comparison to a default of 0.  So any uptime in the range of `0x80000000` to `0xFFFFFFFF` milliseconds (about 24.9 to 49.7 days) will fail the check.

I suppose removing the cast would work (except for a 20 millisecond window every 49.7 days, but whatever).

**Comment by sirocyl** [comment]
There's code in [`netplay.h`](https://github.com/snes9xgit/snes9x/blob/8a5d29c4a9dea22d036f63450cdfa8442fc8fce4/netplay.h#L207) which defines `S9xGetMilliTime` as an alias to `timeGetTime`.

Maybe a good idea to
- bring that code out into `snes9x.h` proper, rather than in the netplay code
- replace direct uses of `timeGetTime()` with `S9xGetMilliTime()`
- is it necessary to `#ifdef` it out on non-win32?
- cast it as uint32 proper, as there's no such thing as negative uptime on a reasonable system :)
