### ISSUE TITLE
No Linux installer for 1.60?

### ISSUE THREAD

**Issue by tehmasterer** [snes9xgit/snes9x#744]
I don't see a Linux installer for the latest release. I want to get snes9x running with Lutris.

I tried to compile the software following the instructions, but **meson** failed because it can't find **Cmake** and **glib-2.0**. I then tried **ninja**, but the **build file** for ninja doesn't exist in the GTK directory. Am I missing something here?

I am running Ubuntu 21.10

**Comment by bearoso** [comment]
Try installing the following packages first:
```build-essential git meson cmake libgtk2.0-dev libgtk-3-dev libsdl2-dev glslang-dev portaudio19-dev libminizip-dev```

It doesn't use cmake, so I'm not sure why you're getting a message about that, but might as well install it anyway.

**Comment by eli-schwartz** [comment]
Meson tries to find every dependency using `pkg-config`. If it cannot find that dependency using `pkg-config`, it will try again to find it using `cmake`, due to the prevalence of software out there that only installs `*-config.cmake` files instead of proper pkg-config files.

glib/gtk definitely install pkg-config files, and don't install cmake's special snowflake files. But if glib/gtk is not installed at all, then it cannot be found with pkg-config, and it will try and again fail using cmake, but you can ignore that.

The error message which Meson fails with would tell you "dependency glib-2.0 found: NO (tried pkg-config and cmake)".

i.e. the ***error*** is that glib-2.0 could not be found. The error is not "cmake could not be found", that's just one of the things it tried.

**Comment by tehmasterer** [comment]
A lot of those packages you listed are not in the requirements list. I don't see glib-2.0 listed in the above packages. I also don't see it listed under wiki > compiling. I do not want to install a bunch of random packages just to do a one-off compile.

Also why is **ninja** shown as an option in the wiki, yet there are no files for it?

**Comment by tehmasterer** [comment]
You will have to forgive my ignorance, because i thought **meson** and **ninja** were two different compilers. Reading the wiki for compiling, I thought I had the choice of one or other. Anyway, I compiled the emulator, which only took about a minute on old hardware. Is there a reason you guys don't compile it for Linux?

Before I posted my issue, I checked for snes9x on the snap store and the repositories. It was removed as you said. Only **higan** and **zsnes** are available.
