### ISSUE TITLE
Satellaview & Super Game Boy Support PLS

### ISSUE THREAD

**Issue by SopTheSop27** [snes9xgit/snes9x#751]
Add Satellaview & Super Game Boy Support

**Comment by OV2** [comment]
There already is some satellaview support. Super Game Boy support seems very unlikely at the moment.

**Comment by SopTheSop27** [comment]
Super Game Boy Cannot Simulate / Doesn't Work On Snes9x

https://user-images.githubusercontent.com/101358042/160005258-186a2c9e-a832-41d1-a75c-fa66abb5eac5.mp4

**Comment by qwertymodo** [comment]
The Super GameBoy is an entire Game Boy console stuffed into a Super Nintendo cartridge.  In order to emulate it, we would need to create an entire Game Boy emulator (or merge in an existing one).  The cartridge will run, as you showed, but the black screen is basically what happens if you rip the Game Boy hardware out of the cart.

**Comment by PatrickStar2007** [comment]
Super Game Boy Cannot Simulate On Snes9x, But Can On bsnes. Simulating Super Game Boy Games Using Subsystem: Using Game Boy / Color Games .gb, .gbc And Super Game Boy Or Super Game Boy 2 SNES. It Works. I Tried With RetroArch bsnes. bsnes Core Is Laggy On Android Devices. Can You Please Add Super Game Boy Subsystem. 1. Game Boy / Color Games (.gb & .gbc) 2. Super Game Boy Or Super Game Boy 2 SNES. 3. Start.

**Comment by SopTheSop27** [comment]
Need Game Boy / Color Support For Snes9x (.gb, .gbc) Using Super Game Boy.
