### ISSUE TITLE
snes9x 1.61 not working on macOS M2 chip

### ISSUE THREAD

**Issue by Zombie10** [snes9xgit/snes9x#819]
I am using snes9x 1.61 but  i can't open any games or settings my gamepad.
[report.txt](https://github.com/snes9xgit/snes9x/files/10776383/report.txt)

**Comment by MichaelBuckley** [comment]
This looks like the problem as
https://github.com/snes9xgit/snes9x/issues/810

It's been fixed in code, but there hasn't been a build since then.

I'm currently traveling, and I don't even have access to github right now.
I'm replying from my email client. I'll see about getting a build when I
return.

**Comment by CatGreen90** [comment]
Mac builds are currently broken due to CirrusCI sunsetting Intel instances: https://cirrus-ci.org/blog/2022/11/08/sunsetting-intel-macos-instances/

**Comment by MichaelBuckley** [comment]
Yes, this is true. I will upload a build from my machine, and try to set up
CirrusCI for ARM64 Macs, next week.

**Comment by MichaelBuckley** [comment]
Sorry for the delay. The CirrusCI config has been updated, and builds are now working again. I've posted a notarized build with the crash fix in #586.
