### ISSUE TITLE
Interlace field bit flipped parity

### ISSUE THREAD

**Issue by DonutSMWC** [snes9xgit/snes9x#821]
I've been experimenting with interlacing, specifically how it can be used to double the vertical resolution of tiles, by timing DMA with interlacing; showing the even pixels of an image one frame, then the odd pixels the other.
Register $213F's highest bit, the 'Interlace Field' bit toggles every v-blank. This came in really handy for timing my DMA code with the interlacing, but I ran into an issue. On snes9x, this bit has flipped parity, meaning that on other emulators and on hardware my code would be synced with interlacing correctly, but on snes9x, it wouldn't, meaning that the odd and even pixels of my image would be swapped.
It's not a big issue, but I think it wouldn't take that much to fix.

**Comment by bearoso** [comment]
Interesting. I've been back and forth on this, and everyone said it was correct how it is currently. 

Based on the Lufia II credit screen, I kind of thought it was the other way around.

This should be easy to check: Change the `Timing.InterlaceField = FALSE;` line at cpu.cpp:78 to `Timing.InterlaceField = TRUE;`
On the other hand, we could also do `Memory.FillRAM[0x213F] |= 0x80;` there instead of changing Timing.InterlaceField.

**Comment by DonutSMWC** [comment]
So... some interesting things... I found out that for whatever reason, rewinding or loading a save state (on an unmodified build) inverts the field bit (making my code sync on snes9x as well). This can and will only happen once.
I tried the fix you suggested, and it didn't fix the parity being flipped. What it did fix, however, is the issue I mentioned above; With `Timings.InterlaceField` set to `TRUE` rewinding or loading save states doesn't cause the fild bit to flip.

**Comment by bearoso** [comment]
Which port of Snes9x are you using? Windows? Gtk? RetroArch?

**Comment by DonutSMWC** [comment]
I'm using the Windows version.

**Comment by bearoso** [comment]
Seems the key thing here is Timings.InterlaceField is set to FALSE on reset. Windows can only save the state every 2 interlaced frames, so when it reloads a state, it sets Timings.Interlace to FALSE. The memory for 0x213F will be restored from the save state, but it will always be the same on Windows because it doesn't split the two frames. So I'll have to check how Timings.InterlaceField compares with 0x213F after a save load on Windows, whether they're opposite or not. Then I'll get rid of Timings.InterlaceField and just use the value stored in 0x213F instead, since we have 2 values doing the same thing right now.

**Comment by bearoso** [comment]
We had three different locations storing the same value. I've condensed them all down to one, so there's no desynchronization.

I've added this to the vulkan branch. Can you check and see if this works now? It'll be here: https://github.com/snes9xgit/snes9x/tree/vulkan instead of the master branch.

**Comment by DonutSMWC** [comment]
It works! The parity's correct and rewinding no longer flips it.
Great job and thank you, I can rest in peace now.

**Comment by bearoso** [comment]
This should now be part of the master branch.
