### ISSUE TITLE
Add 6xBRZ

### ISSUE THREAD

**Issue by dartraiden** [snes9xgit/snes9x#87]
xBRZ 1.4 just [relized](https://sourceforge.net/projects/xbrz/files/xBRZ/), bringing 6xBRZ support

**Comment by vgturtle127** [comment]
Can you post a screenshot of something with no filter and something with 1xBRZ - 5xBRZ, and then finally a screenshot of 6xBRZ for comparison? I have only ever used hq2x and maybe a few others but turned them off since the visual quality of the game usually is degraded with most filters.

What kind of performance do you get with xBRZ as opposed to Eagle, Sai, hq2x, etc.?

**Comment by dartraiden** [comment]
Comparision from official site

https://a.fsdn.com/con/app/proj/xbrz/screenshots/xBRZ%2022.png
https://a.fsdn.com/con/app/proj/xbrz/screenshots/ga.png
https://a.fsdn.com/con/app/proj/xbrz/screenshots/xBRZ%201.png

from [ScalerTest](http://sourceforge.net/projects/xbrz/files/ScalerTest.zip/download) utility:

[HQ4x](https://i.imgur.com/5Xx8jJi.png)
[4xBRZ](https://i.imgur.com/XPyyGOh.png)
[5xBRZ](https://i.imgur.com/3REYCY3.png)
[6xBRZ](https://i.imgur.com/7Fvxpry.png)

**Comment by vgturtle127** [comment]
Alright, I remember seeing some of those images now that I see them.

So xBRZ looks like a slightly better algorithm than HQX. I can't tell the difference between 4xBRZ and 5 or 6xBRZ. But 4xBRZ is really good for SNES and Sega Genesis/Megadrive games it looks like.

Thanks for the info. But how does SNES9X handle filters currently? Are they added custom, or is it a "put x here and it will compile it in/load automatically" kind of thing?

**Comment by Artoria2e5** [comment]
> I can't tell the difference between 4xBRZ and 5 or 6xBRZ.

Check the dimensions on the picture. Apparently it's xbrz for 4x, 5x, and 6x upscaling.

**Comment by OV2** [comment]
5x/6x are already included.
