### ISSUE TITLE
[Feature Request] Add menu option to change location of snes9x.conf file

### ISSUE THREAD

**Issue by aev-git** [snes9xgit/snes9x#903]
I'm using the latest version of snes9x via Flatpak. At least on Linux, the config file is currently stored in the home folder or generated if one isn't found there. This is just a nitpick, but it would be convenient if there was a menu setting to select a config file to load so we didn't have to store it in the home folder.

**Comment by qwertymodo** [comment]
The tricky part there is that "where to store the config file" is a setting you have to store... somewhere, and the most obvious place to store settings is in the main config file, and then you have a circular problem.  Maybe a better option would be to have a list of places where the config file can be located, and we search them in order, then you can place the file in any of those locations and then it will use that file, rather than creating a new one.

**Comment by bearoso** [comment]
Use the environment variable XDG_CONFIG_HOME

**Comment by bearoso** [comment]
I reworked the config directory check. It'll prioritize XDG_CONFIG_HOME/snes9x if it's set, otherwise it uses $HOME/.config/snes9x. On most systems without any sandboxes those will be the same.
