### ISSUE TITLE
On a 4MB SuperFX ROM with a custom XML, the SCMR Register RAN bit behaves as RON bit, causing a lock up and crash.

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#913]
![image](https://github.com/snes9xgit/snes9x/assets/127693805/8810653b-c18c-43ec-8ed6-92580c7985e2)
The issue is, for some reason when SCMR is set to #$0D to hand over control of the RAM to the SuperFX while the program execution is happening in banks +$80, the ROM will lock up and crash snes9x. _This does not happen on bsnes._ (tested on bsnes plus v05)

The offending line of code:

LDY #$0D
STY SFX_SCMR

when this is removed, the program executes just fine. It might be possible that this is also an issue with the XML parser not mapping banks $80+ properly, since the issue does not happen if the code is executed on bank 0 instead.

Test ROM:
[test.zip](https://github.com/snes9xgit/snes9x/files/15046210/test.zip)

Expected result:
![image](https://github.com/snes9xgit/snes9x/assets/127693805/c4a552e6-de06-4a2c-acd8-aa9e74416053)

Error (the emulator crashes shortly after):
![image](https://github.com/snes9xgit/snes9x/assets/127693805/43be9aa8-0703-464c-9a3d-9b02450ca456)

**Comment by bearoso** [comment]
> It might be possible that this is also an issue with the XML parser not mapping banks $80+ properly, since the issue does not happen if the code is executed on bank 0 instead.

I'd say that's very likely, since we don't have an XML parser for memory maps, only the heuristics.

**Comment by bearoso** [comment]
Committed that in [af4ec50](https://github.com/snes9xgit/snes9x/commit/af4ec50b16f267245350ab099dde62a38aec66bd). If it breaks anything that's a problem to fix down the line because it's obviously correct.

**Comment by bearoso** [comment]
Looking further in, the check is actually redundant, so it shouldn't break anything.

**Comment by lordpeluca** [comment]
The update "SuperFX: Run when any bit of SCMR is set." breaks the game "starfox 2".

With the emulator set to "SuperFx speed: 80%" the whole intro of the game looks buggy and freezes in this part:

![1 SFX speed 80](https://github.com/snes9xgit/snes9x/assets/40054709/3269a24e-1752-425f-b235-453e8fc0a319)


It keeps playing the game music, but it doesn't go from there, even if I press start. And I try to skip the intro by pressing start, it just freezes.

With the emulator set to "SuperFx speed: 100% (as default) the intro of the game still looks buggy but I can get to the start screen, but if I press start it just freezes and it also looks buggy like alternating errors, as well as these pictures:

![1 SFX speed 100](https://github.com/snes9xgit/snes9x/assets/40054709/ab7edd5b-5477-4aaf-bdb6-14f2c57c498d)
![2 SFX speed 100](https://github.com/snes9xgit/snes9x/assets/40054709/be910634-b3e5-473f-bb05-d780f9ea350c)


Before the update "SuperFX: Run when any bit of SCMR is set." and with the SuperFx speed 80% setting the game loaded normally (no bugs) and was playable:

![f1](https://github.com/snes9xgit/snes9x/assets/40054709/242d697a-4f89-4fde-ab32-9e877337a406)
![f2](https://github.com/snes9xgit/snes9x/assets/40054709/e3c2fbf0-975a-4cbc-89bb-d8aae56945bd)


PS: Game set to 80% because of a bug in Super Mario World 2: Yoshi's Island, in world 1-4 if yoshi is crushed by the first wall it will fail, it makes like a flicker when it is at 100%.

**Comment by bearoso** [comment]
Yeah, this could make the SuperFX run more often, which means that the speed that was estimated before is useless. On the other hand, we can probably tune it to be more accurate across different games than it was before.

**Comment by lordpeluca** [comment]
Well, I think for now I'll stick with the latest update of snes9x in which starfox 2 (Qt: Implement Swap Controller 1 & 2) worked fine.

Maybe later I will leave this update exclusive for this special game since, as you said in a part of your post above: "If it breaks anything that's a problem to fix down the line because it's obviously correct".

Regards

**Comment by bearoso** [comment]
The permissions are checked in the fx_checkStartAddress function, so those should be correct. Before, it only executed if both flags were set, so it wouldn't have triggered with RAM only before.

The real question is why Snes9x had that in the first place, and if it was working around something or just a mistake.

**Comment by bearoso** [comment]
I changed the code in fx_checkStartAddress to match the banks bsnes checks. This seems to fix Star Fox 2.

**Comment by bearoso** [comment]
I made an additional commit to allow execution for banks 0x80 and above. This still doesn't fix your test ROM, though. It's not mapping those banks and jumping to garbage and never returning. I also made it stop emulation when S9xMainLoop doesn't trigger an hblank after a million cycles. This should fix some of the soft locks we get when running into errors.

**Comment by qwertymodo** [comment]
The GSU chip doesn't physically support more than 16Mbit of ROM.  In fact, the GSU-1 revisions only support 8Mbit, and it is only the later GSU-2 revisions that add another address pin.  The remaining address space mapped to ROM can only contain mirrored data on real hardware.

**Comment by lordpeluca** [comment]
The game works perfectly with the new updates.

Thank you bearoso for fixing it. And thanks to all the guys who participated in the thread for all the information written.

Regards

**Comment by bearoso** [comment]
I went ahead and added your commit. As long as it doesn't break real games, it's fine. We've added support for unrealistic memory maps before.
