### ISSUE TITLE
Emulation runs twice as fast when interlacing is turned on

### ISSUE THREAD

**Issue by DonutSMWC** [snes9xgit/snes9x#930]
In v1.62.3 if interlacing is turned on (LSB of $2133 is set) emulation (includes music too) runs twice as fast. Setting the emulation speed to 50% makes the game run at normal speed.

**Comment by bearoso** [comment]
That's a consequence of  two things:

1. You have rate-limited Snes9x by using vsync at ~60Hz, not using sound sync or timer synchronization.
2. The Windows port doesn't issue a callback for every interlaced pair, only for the full composite, which means the video code isn't called. This means only sound sync will work properly.

Should be fixed in [c7b77d4](https://github.com/snes9xgit/snes9x/commit/c7b77d4a763e8fa3ee2c4ef63b3974527056b7ad).

**Comment by DonutSMWC** [comment]
Interesting. Turning on sound sync did indeed fix it. Thank you!
