### ISSUE TITLE
GTK: Issue with "pause emulation" option

### ISSUE THREAD

**Issue by gilchavezm** [snes9xgit/snes9x#965]
I noticed that activating the option
`Pause emulation when switching away from Snes9x`
causes my GTK build to freeze when trying to open a ROM file, or to freeze the emulation when the ROM is loaded. This also happens with the appimage.

I am using Waylad. Using X11 there is no issue. Also, this does not occur with my Qt build.
Many thanks,

**Comment by bearoso** [comment]
Fixed in [2ffc66c](https://github.com/snes9xgit/snes9x/commit/2ffc66c33ccfb179c46a14d8fe2d9986e27f7f12). It was undefined behavior in Gtk.

**Comment by dCo3lh0** [comment]
just an update, the commit was made in december, while the appimage  is made in july, in AUR the git version available is still 1.62 while the normal pre-compiled version is 1.63, when will the next version 1.64 will be released (even with appimage) with this commit applied? its happening here with me as well making the emulator impossible to use.

**Comment by dCo3lh0** [comment]
well i did adapt here, get the latest nightly build and substituted the binary from snes9x-gtk in /usr/bin its working and now its not freezing, but i hope for an update of the latest version to release with this commit applied, thanks.

**Comment by bearoso** [comment]
This is actually a problem with Wayland itself. It needs the fifo protocol to work correctly. The changes made here are just a workaround and i can't completely fix the OpenGL output. This is fixed in Gnome 48 with Mesa 24.3 or later. KDE will be fixed in 6.4. 

You can also force the Xwayland backend in Gtk by using the environment variable GDK_BACKEND=x11 to get around it. Don't set this globally if you're running Gnome, though.
